on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    uses: rapharw/github-wf-templates/.github/workflows/CI.yaml@v0.0.44-alpha
    with:
      APPLICATION_RUNTIME: angular
      BUILD_COMPILE: npm